spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:myCosmetics;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  profiles:
    include:
      - jwt
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true

  sql:
    init:
      data-locations: classpath:schema-h2.sql
